# Generated by Django 5.2.15 on 2026-07-03 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shyship', '0002_shyshipgame_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='shyshipgame',
            name='bot_state',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='shyshipgame',
            name='vs_bot',
            field=models.BooleanField(default=False),
        ),
    ]
