# Generated by Django 5.2.15 on 2026-06-14 01:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('genre_tone', models.CharField(max_length=100)),
                ('danger_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('sanctuary', 'Sanctuary'), ('all_levels', 'All Levels')], max_length=20)),
                ('is_pvp_zone', models.BooleanField(default=False)),
                ('is_scaled', models.BooleanField(default=False)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('brief_description', models.CharField(max_length=500)),
                ('coord_x', models.IntegerField(default=0)),
                ('coord_y', models.IntegerField(default=0)),
                ('coord_z', models.IntegerField(default=0)),
                ('flag_safe', models.BooleanField(default=False)),
                ('flag_pvp', models.BooleanField(default=False)),
                ('flag_dark', models.BooleanField(default=False)),
                ('flag_indoors', models.BooleanField(default=False)),
                ('flag_water', models.BooleanField(default=False)),
                ('flag_no_recall', models.BooleanField(default=False)),
                ('flag_radiation', models.BooleanField(default=False)),
                ('flag_holy', models.BooleanField(default=False)),
                ('flag_magic_dead', models.BooleanField(default=False)),
                ('flag_scaled', models.BooleanField(default=False)),
                ('exit_down', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entrance_from_above', to='shyland.room')),
                ('exit_east', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entrance_from_west', to='shyland.room')),
                ('exit_north', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entrance_from_south', to='shyland.room')),
                ('exit_south', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entrance_from_north', to='shyland.room')),
                ('exit_up', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entrance_from_below', to='shyland.room')),
                ('exit_west', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entrance_from_east', to='shyland.room')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='shyland.zone')),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('origin', models.CharField(choices=[('highborn', 'Highborn'), ('feral', 'Feral'), ('streetborn', 'Streetborn'), ('irradiated', 'Irradiated'), ('undying', 'Undying'), ('machinekind', 'Machinekind'), ('voidtouched', 'Voidtouched')], max_length=20)),
                ('archetype', models.CharField(choices=[('blade', 'Blade'), ('bulwark', 'Bulwark'), ('shade', 'Shade'), ('conduit', 'Conduit'), ('warden', 'Warden'), ('gunner', 'Gunner'), ('machinist', 'Machinist')], max_length=20)),
                ('level', models.IntegerField(default=1)),
                ('xp', models.IntegerField(default=0)),
                ('stat_str', models.IntegerField(default=10)),
                ('stat_dex', models.IntegerField(default=10)),
                ('stat_end', models.IntegerField(default=10)),
                ('stat_int', models.IntegerField(default=10)),
                ('stat_wis', models.IntegerField(default=10)),
                ('stat_per', models.IntegerField(default=10)),
                ('vitality_current', models.IntegerField(default=100)),
                ('vitality_max', models.IntegerField(default=100)),
                ('acuity_current', models.IntegerField(default=50)),
                ('acuity_baseline', models.IntegerField(default=50)),
                ('acuity_band_low', models.IntegerField(default=35)),
                ('acuity_band_high', models.IntegerField(default=65)),
                ('longevity_current', models.IntegerField(default=100)),
                ('longevity_max', models.IntegerField(default=100)),
                ('copper', models.BigIntegerField(default=0)),
                ('is_hardcore', models.BooleanField(default=False)),
                ('is_dead', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shyland_character', to=settings.AUTH_USER_MODEL)),
                ('current_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='characters', to='shyland.room')),
                ('recall_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recall_characters', to='shyland.room')),
            ],
        ),
        migrations.CreateModel(
            name='RoomVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visited_at', models.DateTimeField(auto_now_add=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_visits', to='shyland.character')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='shyland.room')),
            ],
            options={
                'unique_together': {('character', 'room')},
            },
        ),
    ]
