# Generated by Django 5.2.15 on 2026-06-14 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shyland', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='name',
        ),
    ]
