# Generated by Django 5.2.15 on 2026-06-14 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shyland', '0002_remove_character_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('area_description', models.TextField(blank=True, help_text='Shared atmospheric text for all rooms in this area. Describes the general feel, sounds, smells, and environment. Shown alongside the room-specific description.')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='shyland.zone')),
            ],
            options={
                'ordering': ['zone', 'name'],
            },
        ),
        migrations.AddField(
            model_name='room',
            name='area',
            field=models.ForeignKey(blank=True, help_text='Optional. Groups this room with others sharing a common atmosphere.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms', to='shyland.area'),
        ),
    ]
