# Generated by Django 5.2.15 on 2026-06-15 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shyland', '0003_area_room_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='EffectDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('effect_type', models.CharField(choices=[('restore_vitality', 'Restore Vitality'), ('restore_acuity', 'Restore Acuity'), ('restore_longevity', 'Restore Longevity'), ('dot_vitality', 'DoT Vitality'), ('dot_acuity', 'DoT Acuity'), ('dot_longevity', 'DoT Longevity'), ('shift_acuity_high', 'Shift Acuity High'), ('shift_acuity_low', 'Shift Acuity Low'), ('stat_bonus', 'Stat Bonus'), ('stat_penalty', 'Stat Penalty'), ('durability_restore', 'Durability Restore'), ('curse_generic', 'Curse Generic')], max_length=30)),
                ('magnitude_min', models.FloatField()),
                ('magnitude_max', models.FloatField()),
                ('duration_min', models.FloatField(blank=True, null=True)),
                ('duration_max', models.FloatField(blank=True, null=True)),
                ('scales_with_mk', models.BooleanField(default=False)),
                ('scaling_base', models.FloatField(blank=True, null=True)),
                ('scaling_factor', models.FloatField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='EffectInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_ability', models.CharField(blank=True, max_length=100)),
                ('magnitude', models.FloatField()),
                ('duration', models.FloatField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('removed_by', models.CharField(blank=True, max_length=50)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='shyland.effectdefinition')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_effects', to='shyland.character')),
            ],
        ),
        migrations.CreateModel(
            name='ItemDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('item_type', models.CharField(choices=[('weapon', 'Weapon'), ('armor', 'Armor'), ('accessory', 'Accessory'), ('consumable', 'Consumable'), ('bag', 'Bag'), ('readable', 'Readable'), ('key', 'Key')], max_length=20)),
                ('genre_tag', models.CharField(choices=[('fantasy', 'Fantasy'), ('cyber', 'Cyber'), ('wasteland', 'Wasteland'), ('gothic', 'Gothic'), ('steam', 'Steam'), ('cosmic', 'Cosmic')], max_length=20)),
                ('description', models.TextField()),
                ('scaling_base', models.FloatField()),
                ('scaling_factor', models.FloatField()),
                ('damage_spread', models.FloatField(blank=True, null=True)),
                ('is_ranged', models.BooleanField(default=False)),
                ('valid_slots', models.JSONField(default=list)),
                ('is_two_handed', models.BooleanField(default=False)),
                ('takes_durability_loss', models.BooleanField(default=True)),
                ('durability_table', models.JSONField(default=list)),
                ('carry_bonus', models.IntegerField(default=0)),
                ('primary_stats', models.JSONField(default=list)),
                ('secondary_stat_pool', models.JSONField(default=list)),
                ('is_cursed_template', models.BooleanField(default=False)),
                ('effect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='shyland.effectdefinition')),
            ],
        ),
        migrations.CreateModel(
            name='ItemInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mk_tier', models.IntegerField()),
                ('rarity', models.CharField(choices=[('common', 'Common'), ('uncommon', 'Uncommon'), ('rare', 'Rare'), ('epic', 'Epic'), ('legendary', 'Legendary'), ('artifact', 'Artifact')], max_length=20)),
                ('rolled_primary_stats', models.JSONField(default=list)),
                ('rolled_secondary_stats', models.JSONField(default=list)),
                ('damage_midpoint', models.FloatField(blank=True, null=True)),
                ('damage_spread', models.FloatField(blank=True, null=True)),
                ('durability_current', models.FloatField(default=100.0)),
                ('is_broken', models.BooleanField(default=False)),
                ('is_soulbound', models.BooleanField(default=False)),
                ('is_equipped', models.BooleanField(default=False)),
                ('equipped_slot', models.CharField(blank=True, max_length=20)),
                ('is_cursed', models.BooleanField(default=False)),
                ('curse_identified', models.BooleanField(default=False)),
                ('is_artifact', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('active_curse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cursed_item', to='shyland.effectinstance')),
                ('current_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='shyland.room')),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='shyland.itemdefinition')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory', to='shyland.character')),
                ('soulbound_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='soulbound_items', to='shyland.character')),
            ],
        ),
        migrations.AddField(
            model_name='effectinstance',
            name='source_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_effects', to='shyland.iteminstance'),
        ),
    ]
