# Generated by Django 5.2.15 on 2026-06-16 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shyland', '0004_effectdefinition_effectinstance_itemdefinition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemdefinition',
            name='mystery_description',
            field=models.TextField(blank=True, help_text="Description shown on examine before identification. Can contain lore, atmosphere, or deliberate misdirection. If blank, falls back to 'You can't determine anything about this item.'"),
        ),
        migrations.AddField(
            model_name='itemdefinition',
            name='mystery_name',
            field=models.CharField(blank=True, help_text="Name shown to players before identification. e.g. 'an unknown sword', 'a fragment of something'. If blank, falls back to 'an unidentified <item_type>'.", max_length=200),
        ),
        migrations.AddField(
            model_name='iteminstance',
            name='is_identified',
            field=models.BooleanField(default=True, help_text="Whether this item's true nature is known to its current holder. Defaults True — set False on items that should be mysterious. Resets to False when the item is dropped."),
        ),
        migrations.AddField(
            model_name='iteminstance',
            name='is_unidentifiable',
            field=models.BooleanField(default=False, help_text='If True, no in-game mechanism can ever identify this item. Set by super users only on specific instances. Intended for one-of-a-kind mystery Artifacts.'),
        ),
    ]
