# Generated by Django 5.2.15 on 2026-06-16 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shyland', '0005_itemdefinition_mystery_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LootTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Corpse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('npc_name_snapshot', models.CharField(help_text='NPC name captured at death. Stable reference.', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decay_at', models.DateTimeField(help_text='Corpse and all contents deleted at this time. Sweep deferred to tick engine.')),
                ('copper_drop', models.BigIntegerField(default=0, help_text='Copper to transfer to killer on first loot. Set at death.')),
                ('current_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corpses', to='shyland.room')),
                ('killed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kills', to='shyland.character')),
            ],
        ),
        migrations.AddField(
            model_name='iteminstance',
            name='corpse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contents', to='shyland.corpse'),
        ),
        migrations.CreateModel(
            name='LootTableEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mk_tier_min', models.IntegerField()),
                ('mk_tier_max', models.IntegerField()),
                ('drop_chance', models.FloatField(help_text='0.0 to 1.0. Rolled independently per entry.')),
                ('rarity_weights', models.JSONField(default=dict, help_text='Dict of rarity → weight. Keys: common, uncommon, rare, epic, legendary. Must sum to 100.')),
                ('item_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shyland.itemdefinition')),
                ('loot_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='shyland.loottable')),
            ],
        ),
        migrations.CreateModel(
            name='NpcDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(help_text='Shown when a player examines the NPC.')),
                ('genre_tag', models.CharField(choices=[('fantasy', 'Fantasy'), ('cyber', 'Cyber'), ('wasteland', 'Wasteland'), ('gothic', 'Gothic'), ('steam', 'Steam'), ('cosmic', 'Cosmic')], max_length=20)),
                ('is_aggressive', models.BooleanField(default=False, help_text='Attacks players on sight.')),
                ('is_unique', models.BooleanField(default=False, help_text='One instance only; no respawn.')),
                ('wanders', models.BooleanField(default=False, help_text='Moves between rooms. Not yet implemented.')),
                ('base_vitality', models.IntegerField()),
                ('base_str', models.IntegerField()),
                ('base_dex', models.IntegerField()),
                ('base_end', models.IntegerField()),
                ('base_int', models.IntegerField()),
                ('base_wis', models.IntegerField()),
                ('base_per', models.IntegerField()),
                ('scaling_factor', models.FloatField(default=1.0, help_text='Stat multiplier per Mk tier.')),
                ('currency_drop_min', models.IntegerField(default=0, help_text='Minimum copper drop (before Mk scaling).')),
                ('currency_drop_max', models.IntegerField(default=0, help_text='Maximum copper drop (before Mk scaling).')),
                ('respawn_minutes', models.IntegerField(default=30, help_text='Ignored if is_unique=True.')),
                ('loot_table', models.ForeignKey(blank=True, help_text='Loot table rolled on death. Null = no item drops.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='shyland.loottable')),
            ],
        ),
        migrations.AddField(
            model_name='corpse',
            name='npc_definition',
            field=models.ForeignKey(blank=True, help_text='Source NPC definition. SET_NULL so corpse survives definition deletion.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='shyland.npcdefinition'),
        ),
        migrations.CreateModel(
            name='NpcInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mk_tier', models.IntegerField(default=1)),
                ('vitality_current', models.IntegerField()),
                ('vitality_max', models.IntegerField()),
                ('is_alive', models.BooleanField(default=True)),
                ('spawned_at', models.DateTimeField(auto_now_add=True)),
                ('respawn_at', models.DateTimeField(blank=True, help_text='Set on death. Null while alive.', null=True)),
                ('current_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='npcs', to='shyland.room')),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='shyland.npcdefinition')),
            ],
        ),
    ]
