# Generated by Django 5.2.15 on 2026-06-17 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shyland', '0006_loottable_corpse_iteminstance_corpse_loottableentry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='npcinstance',
            name='spawn_room',
            field=models.ForeignKey(blank=True, help_text='The room this NPC spawns into. Used for respawn. Set at creation time.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='npc_spawns', to='shyland.room'),
        ),
    ]
