# Generated by Django 5.2.15 on 2026-06-18 20:48

import django.db.models.deletion
from django.db import migrations, models


_ACUITY_DEFAULTS = {
    'highborn':    (1.0,  0.85, 1.15),
    'feral':       (0.95, 0.80, 1.10),
    'streetborn':  (1.0,  0.85, 1.15),
    'irradiated':  (0.90, 0.75, 1.05),
    'undying':     (0.80, 0.65, 1.00),
    'machinekind': (1.05, 0.90, 1.20),
    'voidtouched': (0.70, 0.40, 1.30),
}


def reset_acuity_defaults(apps, schema_editor):
    Character = apps.get_model('shyland', 'Character')
    for character in Character.objects.all():
        baseline, band_low, band_high = _ACUITY_DEFAULTS.get(
            character.origin, (1.0, 0.8, 1.2)
        )
        character.acuity_current = baseline
        character.acuity_baseline = baseline
        character.acuity_band_low = band_low
        character.acuity_band_high = band_high
        character.save(update_fields=['acuity_current', 'acuity_baseline', 'acuity_band_low', 'acuity_band_high'])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('shyland', '0007_npcinstance_spawn_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='dying_since',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='is_dying',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='character',
            name='acuity_band_high',
            field=models.FloatField(default=1.2),
        ),
        migrations.AlterField(
            model_name='character',
            name='acuity_band_low',
            field=models.FloatField(default=0.8),
        ),
        migrations.AlterField(
            model_name='character',
            name='acuity_baseline',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='character',
            name='acuity_current',
            field=models.FloatField(default=1.0),
        ),
        migrations.RunPython(reset_acuity_defaults, reverse_code=noop),
        migrations.CreateModel(
            name='CombatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_tick_at', models.DateTimeField(blank=True, null=True)),
                ('tick_counter', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('first_attacker', models.CharField(default='character', max_length=20)),
                ('last_flee_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('characters', models.ManyToManyField(blank=True, related_name='combat_sessions', to='shyland.character')),
                ('last_flee_character', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='shyland.character')),
                ('npcs', models.ManyToManyField(blank=True, related_name='combat_sessions', to='shyland.npcinstance')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='combat_sessions', to='shyland.room')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='CombatAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('attack', 'Attack'), ('use', 'Use Item'), ('flee', 'Flee')], default='attack', max_length=20)),
                ('queued_at', models.DateTimeField(auto_now_add=True)),
                ('is_processed', models.BooleanField(default=False)),
                ('character', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='combat_actions', to='shyland.character')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='combat_actions', to='shyland.iteminstance')),
                ('npc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='combat_actions', to='shyland.npcinstance')),
                ('target_character', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targeted_by_actions', to='shyland.character')),
                ('target_npc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targeted_by_actions', to='shyland.npcinstance')),
                ('combat_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='shyland.combatsession')),
            ],
            options={
                'ordering': ['queued_at'],
            },
        ),
        migrations.CreateModel(
            name='NpcEffect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effect_chance', models.FloatField(default=1.0)),
                ('effect_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shyland.effectdefinition')),
                ('npc_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='effects', to='shyland.npcdefinition')),
            ],
            options={
                'ordering': ['npc_definition', 'effect_definition'],
            },
        ),
    ]
