# Generated by Django 5.2.15 on 2026-06-19 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shyland', '0009_reset_acuity_to_float_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='unspent_stat_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='effectdefinition',
            name='target_stat',
            field=models.CharField(blank=True, choices=[('str', 'Strength'), ('dex', 'Dexterity'), ('end', 'Endurance'), ('int', 'Intelligence'), ('wis', 'Wisdom'), ('per', 'Perception')], max_length=10),
        ),
    ]
