# Generated by Django 5.2.15 on 2026-06-20 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shyland', '0010_character_unspent_stat_points_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='effectdefinition',
            name='duration_max',
        ),
        migrations.RemoveField(
            model_name='effectdefinition',
            name='duration_min',
        ),
        migrations.RemoveField(
            model_name='effectdefinition',
            name='effect_type',
        ),
        migrations.RemoveField(
            model_name='effectdefinition',
            name='magnitude_max',
        ),
        migrations.RemoveField(
            model_name='effectdefinition',
            name='magnitude_min',
        ),
        migrations.RemoveField(
            model_name='effectdefinition',
            name='scales_with_mk',
        ),
        migrations.RemoveField(
            model_name='effectdefinition',
            name='scaling_base',
        ),
        migrations.RemoveField(
            model_name='effectdefinition',
            name='scaling_factor',
        ),
        migrations.RemoveField(
            model_name='effectdefinition',
            name='target_stat',
        ),
        migrations.RemoveField(
            model_name='effectinstance',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='effectinstance',
            name='expires_at',
        ),
        migrations.RemoveField(
            model_name='effectinstance',
            name='magnitude',
        ),
        migrations.RemoveField(
            model_name='effectinstance',
            name='source_ability',
        ),
        migrations.RemoveField(
            model_name='effectinstance',
            name='source_item',
        ),
        migrations.AddField(
            model_name='effectinstance',
            name='mk_tier',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='EffectComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_type', models.CharField(choices=[('restore_vitality', 'Restore Vitality'), ('restore_acuity', 'Restore Acuity'), ('restore_longevity', 'Restore Longevity'), ('dot_vitality', 'DoT Vitality'), ('dot_acuity', 'DoT Acuity'), ('dot_longevity', 'DoT Longevity'), ('hot_vitality', 'HoT Vitality'), ('hot_acuity', 'HoT Acuity'), ('hot_longevity', 'HoT Longevity'), ('shift_acuity_high', 'Shift Acuity High'), ('shift_acuity_low', 'Shift Acuity Low'), ('stat_bonus', 'Stat Bonus'), ('stat_penalty', 'Stat Penalty'), ('curse_generic', 'Curse Generic'), ('durability_restore', 'Durability Restore')], max_length=30)),
                ('target_stat', models.CharField(blank=True, choices=[('str', 'STR'), ('dex', 'DEX'), ('end', 'END'), ('int', 'INT'), ('wis', 'WIS'), ('per', 'PER')], max_length=10)),
                ('magnitude_base', models.FloatField()),
                ('magnitude_scaling', models.FloatField(default=0.0)),
                ('duration_base', models.FloatField(default=0.0)),
                ('duration_scaling', models.FloatField(default=0.0)),
                ('order', models.IntegerField(default=0)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='shyland.effectdefinition')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='EffectComponentInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('magnitude', models.FloatField()),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('removed_by', models.CharField(blank=True, max_length=50)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shyland.effectcomponent')),
                ('effect_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_instances', to='shyland.effectinstance')),
            ],
        ),
    ]
