# Generated by Django 5.2.15 on 2026-06-27 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shyland', '0011_remove_effectdefinition_duration_max_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='brief_mode',
            field=models.BooleanField(default=False),
        ),
    ]
