# Generated by Django 5.2.15 on 2026-06-27 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shyland', '0012_character_brief_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archetype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('primary_stat_1', models.CharField(choices=[('str', 'STR'), ('dex', 'DEX'), ('end', 'END'), ('int', 'INT'), ('wis', 'WIS'), ('per', 'PER')], max_length=3)),
                ('primary_stat_2', models.CharField(choices=[('str', 'STR'), ('dex', 'DEX'), ('end', 'END'), ('int', 'INT'), ('wis', 'WIS'), ('per', 'PER')], max_length=3)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Origin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('acuity_baseline', models.FloatField()),
                ('acuity_band_low', models.FloatField()),
                ('acuity_band_high', models.FloatField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UnarmedMessagePool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='character',
            name='archetype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='characters', to='shyland.archetype'),
        ),
        migrations.AlterField(
            model_name='character',
            name='origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='characters', to='shyland.origin'),
        ),
        migrations.CreateModel(
            name='UnarmedMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.TextField(help_text='Python format string. Use {target} for the target name. Example: "You punch {target}."')),
                ('order', models.IntegerField(default=0)),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='shyland.unarmedmessagepool')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='archetype',
            name='unarmed_message_pool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archetypes', to='shyland.unarmedmessagepool'),
        ),
        migrations.AddField(
            model_name='npcdefinition',
            name='unarmed_message_pool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='npc_definitions', to='shyland.unarmedmessagepool'),
        ),
    ]
