# Generated by Django 5.2.15 on 2026-06-28 00:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shyland', '0015_character_origin_archetype_nonnull'),
    ]

    operations = [
        migrations.AddField(
            model_name='npcdefinition',
            name='combat_tier',
            field=models.CharField(choices=[('normal', 'Normal'), ('elite', 'Elite'), ('champion', 'Champion'), ('boss', 'Boss'), ('world_boss', 'World Boss')], default='normal', help_text='Combat role tier. Used for display and future AI/balance logic.', max_length=20),
        ),
        migrations.AddField(
            model_name='room',
            name='no_exit_down_msg',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='room',
            name='no_exit_east_msg',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='room',
            name='no_exit_north_msg',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='room',
            name='no_exit_south_msg',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='room',
            name='no_exit_up_msg',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='room',
            name='no_exit_west_msg',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.CreateModel(
            name='ZoneGate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Display name shown to players (e.g. 'The Northern Rift Gate').", max_length=100)),
                ('description', models.TextField(blank=True, help_text='Flavor text shown when a player examines the gate.')),
                ('is_bidirectional', models.BooleanField(default=True, help_text='If True, this gate can be used in both directions. The travel command will check both source_room and destination_room.')),
                ('requires_discovery', models.BooleanField(default=True, help_text='If True, character must have visited the source room (RoomVisit record exists) before using this gate from elsewhere.')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive gates are invisible and unusable.')),
                ('destination_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gates_to', to='shyland.room')),
                ('source_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gates_from', to='shyland.room')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RoomSpawn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mk_tier', models.IntegerField(default=1, help_text='Mk tier at which this NPC spawns in this room.')),
                ('count', models.IntegerField(default=1, help_text='Desired number of live instances of this NPC in this room.')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive spawns are ignored by the tick engine.')),
                ('npc_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_spawns', to='shyland.npcdefinition')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spawns', to='shyland.room')),
            ],
            options={
                'ordering': ['room', 'npc_definition', 'mk_tier'],
                'unique_together': {('room', 'npc_definition', 'mk_tier')},
            },
        ),
        migrations.CreateModel(
            name='VendorEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mk_tier', models.IntegerField(default=1, help_text='Mk tier of the item being sold.')),
                ('price', models.BigIntegerField(help_text='Price in copper. Always required — no auto-calculation.')),
                ('stock_limit', models.IntegerField(blank=True, help_text='Maximum number of this item available for purchase. Null = unlimited stock.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive entries are hidden from players.')),
                ('item_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_entries', to='shyland.itemdefinition')),
                ('npc_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_entries', to='shyland.npcdefinition')),
            ],
            options={
                'ordering': ['npc_definition', 'item_definition', 'mk_tier'],
                'unique_together': {('npc_definition', 'item_definition', 'mk_tier')},
            },
        ),
    ]
