# Generated by Django 5.2.16 on 2026-07-07 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shyland', '0017_archetype_attire_silhouette_character_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemdefinition',
            name='suppress_mk_suffix',
            field=models.BooleanField(default=False, help_text='If True, display names never show the "Mk N" suffix. Used for tier-material items (copper/silver/gold/platinum) whose material name already conveys the tier.'),
        ),
    ]
