# Generated by Django 5.2.16 on 2026-07-07 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shyland', '0018_itemdefinition_suppress_mk_suffix'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('traveler', 'Traveler'), ('departure', 'Departure witness'), ('arrival', 'Arrival witness')], max_length=12)),
                ('text', models.TextField(help_text="Witness messages may include {name}, replaced with the traveling character's name. Traveler messages take no placeholders.")),
            ],
        ),
        migrations.CreateModel(
            name='TravelNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travel_name', models.CharField(help_text='Unique, typeable destination name shown in travel lists (e.g. "Fordwatch", "The Verdant Crown").', max_length=60, unique=True)),
                ('node_type', models.CharField(choices=[('obelisk', 'Obelisk'), ('checkpoint', 'Checkpoint')], help_text='Obelisks are travel sources and destinations. Checkpoints are destinations only.', max_length=12)),
                ('room', models.OneToOneField(help_text='The room this node lives in. One node per room.', on_delete=django.db.models.deletion.CASCADE, related_name='travel_node', to='shyland.room')),
            ],
        ),
        migrations.DeleteModel(
            name='ZoneGate',
        ),
    ]
