# Generated by Django 5.2.16 on 2026-07-08 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shyland', '0019_travelmessage_travelnode_delete_zonegate'),
    ]

    operations = [
        migrations.AddField(
            model_name='loottableentry',
            name='guaranteed_group',
            field=models.CharField(blank=True, default='', help_text='Optional group label (e.g. "weapon"). At roll time, each distinct group in a table yields EXACTLY ONE of its entries, chosen with drop_chance as relative weight. Grouped entries do not make independent drop rolls. Blank = normal independent roll.', max_length=40),
        ),
        migrations.AddField(
            model_name='npcdefinition',
            name='death_message',
            field=models.TextField(blank=True, default='', help_text='Optional. Broadcast once to the room at the moment this NPC dies, before corpse/loot output. Used for boss narrative reveals (e.g. a guarded chest splitting open). Blank = no extra message.'),
        ),
        migrations.AddField(
            model_name='roomspawn',
            name='requires_living_npc',
            field=models.ForeignKey(blank=True, help_text='If set, this spawn only refills while a live instance of the given definition exists in the same room. Used to gate boss minions on their boss: minions respawn on their own timer while the boss lives, stop when it dies, and resume when it respawns.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependent_spawns', to='shyland.npcdefinition'),
        ),
    ]
