# Generated by Django 5.2.16 on 2026-07-10 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shyland', '0021_itemdefinition_base_value_npcdefinition_is_repairer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='combatsession',
            name='focus_npc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='shyland.npcinstance'),
        ),
    ]
