# Generated by Django 5.2.16 on 2026-07-12 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shyland', '0023_boss_scaling_factor_corrections'),
    ]

    operations = [
        migrations.AddField(
            model_name='npcdefinition',
            name='attackable',
            field=models.BooleanField(default=True, help_text='If False, this NPC may never be targeted, engaged, or hold aggro. Independent of room safe-flag mechanics.'),
        ),
        migrations.AddField(
            model_name='npcdefinition',
            name='is_fixture',
            field=models.BooleanField(default=False, help_text='Displayed in the room\'s "What\'s here?" section instead of "Who\'s here?". Purely a display distinction.'),
        ),
        migrations.AlterField(
            model_name='character',
            name='brief_mode',
            field=models.BooleanField(default=True),
        ),
    ]
