# Generated by Django 5.2.16 on 2026-07-12 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shyland', '0024_npcdefinition_attackable_npcdefinition_is_fixture_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DialogueConnective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_class', models.CharField(choices=[('second', 'Second speaker'), ('later', 'Third-and-later speaker')], max_length=6)),
                ('template', models.TextField(help_text="Uses {name}, replaced with the responding NPC's name.")),
            ],
        ),
        migrations.CreateModel(
            name='DialogueEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('keyword', 'Keyword'), ('greeting', 'Greeting'), ('departed', 'Departed')], default='keyword', max_length=10)),
                ('keywords', models.JSONField(blank=True, default=list, help_text='Lowercase single-word tokens. Empty for greeting/departed entries.')),
                ('note', models.CharField(blank=True, help_text='Authoring aid only.', max_length=100)),
                ('npc_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dialogue_entries', to='shyland.npcdefinition')),
            ],
        ),
        migrations.CreateModel(
            name='DialogueResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='shyland.dialogueentry')),
            ],
        ),
        migrations.CreateModel(
            name='PendingDialogueResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utterance_id', models.UUIDField(help_text='Groups every responder to one say or greeting event.')),
                ('position', models.PositiveSmallIntegerField(help_text='0 = first speaker in this utterance.')),
                ('is_final', models.BooleanField(default=False, help_text='Last speaker for this utterance.')),
                ('fire_at', models.DateTimeField()),
                ('character', models.ForeignKey(help_text='The character whose speech or room entry triggered this response.', on_delete=django.db.models.deletion.CASCADE, related_name='pending_dialogue_responses', to='shyland.character')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_responses', to='shyland.dialogueentry')),
                ('npc_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_dialogue_responses', to='shyland.npcinstance')),
                ('room', models.ForeignKey(help_text='Delivery room, captured at scheduling time so a departed asker cannot silence it.', on_delete=django.db.models.deletion.CASCADE, related_name='pending_dialogue_responses', to='shyland.room')),
            ],
            options={
                'ordering': ['fire_at', 'position'],
            },
        ),
        migrations.CreateModel(
            name='DialogueGreetingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dialogue_greeting_records', to='shyland.character')),
                ('npc_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='greeting_records', to='shyland.npcdefinition')),
            ],
            options={
                'unique_together': {('character', 'npc_definition')},
            },
        ),
    ]
