# Generated by Django 5.2.16 on 2026-07-14 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shyland', '0025_dialogueconnective_dialogueentry_dialogueresponse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='exit_east_boundary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='exit_north_boundary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='exit_south_boundary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='exit_west_boundary',
            field=models.BooleanField(default=False),
        ),
    ]
