# Generated by Django 5.2.16 on 2026-07-15 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shyland', '0026_room_exit_east_boundary_room_exit_north_boundary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='show_timestamps',
            field=models.BooleanField(default=True),
        ),
    ]
