# Generated by Django 5.2.16 on 2026-07-15 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shyland', '0027_character_show_timestamps'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='theme_color',
            field=models.CharField(default='#CCCCCC', max_length=7),
        ),
        migrations.AddField(
            model_name='zone',
            name='theme_color',
            field=models.CharField(default='#CCCCCC', max_length=7),
        ),
    ]
