# Generated by Django 5.2 on 2026-07-15 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shyland', '0028_area_theme_color_zone_theme_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='npcdefinition',
            name='article',
            field=models.CharField(blank=True, default='the', help_text='Article used in composed references ("the", "a", "an"). Blank for proper nouns (Morra, VND-9).', max_length=8),
        ),
        migrations.AddField(
            model_name='npcdefinition',
            name='plural_phrase',
            field=models.CharField(blank=True, help_text='Used verbatim as the composed reference when set — for group-phrase names ("one of the Matron\'s brood").', max_length=64),
        ),
        migrations.AlterField(
            model_name='npcdefinition',
            name='name',
            field=models.CharField(help_text='Article-free (authoring law, enforced by the seed verify): "Silk Matron", "cave spider" — never "the Silk Matron".', max_length=200),
        ),
    ]
