# Generated by Django 5.2 on 2026-07-16 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shyland', '0029_npcdefinition_article_npcdefinition_plural_phrase_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='npcdefinition',
            name='indefinite_article',
            field=models.CharField(blank=True, default='a', help_text='Article for first-presentation contexts ("a", "an"). Blank for proper nouns, bosses, and unique landmarks — they introduce with their definite/bare form.', max_length=8),
        ),
    ]
