# Generated by Django 5.2.16 on 2026-07-19 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shyland', '0030_npcdefinition_indefinite_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='echo_mode',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='brief_mode',
            field=models.BooleanField(default=False),
        ),
    ]
