# Generated by Django 5.2.16 on 2026-07-20 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shyland', '0031_character_echo_mode_alter_character_brief_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelnode',
            name='listing_description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
