# Generated by Django 5.2.16 on 2026-07-20 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shyland', '0032_travelnode_listing_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='home_cooldown_seconds',
            field=models.PositiveIntegerField(default=900, help_text='Per-player home cooldown override (seconds); edit here in the admin to change one character.'),
        ),
        migrations.AddField(
            model_name='character',
            name='home_last_completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='last_connect',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
