# Generated by Django 5.2.16 on 2026-07-24 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shyland', '0034_create_shyland_admin_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iteminstance',
            name='corpse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='shyland.corpse'),
        ),
    ]
