# Generated by Django 5.2.16 on 2026-07-24 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shyland', '0035_alter_iteminstance_corpse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='npcdefinition',
            name='scaling_factor',
            field=models.FloatField(default=1.0, help_text='Within-band level (1-10); Mk tier lifts the effective level by whole bands. See combat_utils.npc_level().'),
        ),
    ]
