# Generated by Django 5.2.16 on 2026-07-25 00:55
"""v23 B4 (#146): remove the dead ItemInstance.is_artifact boolean.

Read by no code, written by nothing, surfaced only as an
authoritative-looking admin checkbox — a trap for hand-authored
artifacts, which are protected by rarity, the single artifact marker."""

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shyland', '0036_alter_npcdefinition_scaling_factor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iteminstance',
            name='is_artifact',
        ),
    ]
