# Generated by Django 5.2.16 on 2026-07-29 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shyland', '0037_remove_iteminstance_is_artifact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='home_cooldown_seconds',
            field=models.PositiveIntegerField(default=300, help_text='Per-player home cooldown override (seconds); edit here in the admin to change one character.'),
        ),
    ]
