# Generated by Django 5.2.16 on 2026-08-01 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shyland', '0039_home_cooldown_reset_300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='effectcomponent',
            name='component_type',
            field=models.CharField(choices=[('restore_vitality', 'Restore Vitality'), ('restore_vitality_percent', 'Restore Vitality (percent of max)'), ('restore_acuity', 'Restore Acuity'), ('restore_longevity', 'Restore Longevity'), ('dot_vitality', 'DoT Vitality'), ('dot_acuity', 'DoT Acuity'), ('dot_longevity', 'DoT Longevity'), ('hot_vitality', 'HoT Vitality'), ('hot_acuity', 'HoT Acuity'), ('hot_longevity', 'HoT Longevity'), ('shift_acuity_high', 'Shift Acuity High'), ('shift_acuity_low', 'Shift Acuity Low'), ('stat_bonus', 'Stat Bonus'), ('stat_penalty', 'Stat Penalty'), ('curse_generic', 'Curse Generic'), ('durability_restore', 'Durability Restore')], max_length=30),
        ),
    ]
