# Generated by Django 5.2.16 on 2026-08-02 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shyland', '0040_alter_effectcomponent_component_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemdefinition',
            name='armor_base',
            field=models.FloatField(default=0.0, help_text='Authored base armor per Mk tier (#129): TAV adds armor_base x mk_tier for every equipped, non-broken instance. 0 = authors no protection. Rarity-blind; rolled physical_resist is bonus on top.'),
        ),
    ]
