# Generated by Django 5.2.17 on 2026-08-12 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shyland', '0041_itemdefinition_armor_base'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemdefinition',
            old_name='carry_bonus',
            new_name='carry_pct_base',
        ),
        migrations.AddField(
            model_name='itemdefinition',
            name='carry_pct_per_mk',
            field=models.IntegerField(default=0),
        ),
    ]
