# Generated by Django 5.2.17 on 2026-08-13 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shyland', '0042_rename_carry_bonus_itemdefinition_carry_pct_base_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='entry_requires_zone',
            field=models.ForeignKey(blank=True, help_text='To enter this zone, a character must have fully explored the named zone (GDD §2.12). Seed-authored; null = open.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unlocked_by', to='shyland.zone'),
        ),
        migrations.CreateModel(
            name='ZoneCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zone_completions', to='shyland.character')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='shyland.zone')),
            ],
            options={
                'unique_together': {('character', 'zone')},
            },
        ),
    ]
