# Generated by Django 5.2.17 on 2026-08-13 00:13

from django.db import migrations
from django.db.models import Count


def grandfather_zone_completions(apps, schema_editor):
    """V24.25 (#41): grandfather keys for every character existing at deploy
    time — the Convergence unconditionally, plus honestly computed keys for
    every zone their RoomVisit record already completes (GDD §2.12). Keys are
    permanent; this migration only creates rows, never deletes."""
    Character = apps.get_model('shyland', 'Character')
    Zone = apps.get_model('shyland', 'Zone')
    RoomVisit = apps.get_model('shyland', 'RoomVisit')
    ZoneCompletion = apps.get_model('shyland', 'ZoneCompletion')

    convergence = Zone.objects.filter(slug='the-convergence').first()

    zone_room_counts = {
        zone.pk: zone.room_count
        for zone in Zone.objects.annotate(room_count=Count('rooms'))
        if zone.room_count > 0
    }

    for character in Character.objects.all():
        if convergence is not None:
            ZoneCompletion.objects.get_or_create(
                character=character, zone=convergence)
        visit_counts = (
            RoomVisit.objects.filter(character=character)
            .values('room__zone')
            .annotate(n=Count('room', distinct=True))
        )
        for row in visit_counts:
            zone_pk = row['room__zone']
            if convergence is not None and zone_pk == convergence.pk:
                continue
            if zone_room_counts.get(zone_pk) == row['n']:
                ZoneCompletion.objects.get_or_create(
                    character=character, zone_id=zone_pk)


class Migration(migrations.Migration):

    dependencies = [
        ('shyland', '0043_zone_entry_requires_zone_zonecompletion'),
    ]

    operations = [
        # Reverse is a deliberate no-op: keys are never revoked, including
        # by rollback.
        migrations.RunPython(grandfather_zone_completions,
                             migrations.RunPython.noop),
    ]
