# Generated by Django 5.2.17 on 2026-08-13 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shyland', '0044_grandfather_zone_completions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='recall_room',
        ),
        migrations.AddField(
            model_name='character',
            name='attuned_node',
            field=models.ForeignKey(blank=True, help_text="The character's home node (GDD §2.11, Attunement): where 'home' delivers and where death respawn wakes. Null = the founding node (the Heart of the Convergence).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attuned_characters', to='shyland.travelnode'),
        ),
        migrations.AlterField(
            model_name='travelnode',
            name='node_type',
            field=models.CharField(choices=[('obelisk', 'Obelisk'), ('checkpoint', 'Checkpoint')], help_text='Obelisks send to every revealed node. Checkpoints relay to revealed obelisks only (GDD §2.11, v24.26).', max_length=12),
        ),
    ]
