# Generated by Django 5.2.17 on 2026-08-14 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shyland', '0045_remove_character_recall_room_character_attuned_node_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iteminstance',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='shyland.character'),
        ),
    ]
