# Generated by Django 5.2.17 on 2026-08-15 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shyland', '0048_itemdefinition_tier_material_mk_max_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='plunder_mode',
            field=models.BooleanField(default=False),
        ),
    ]
