# Generated by Django 5.2.17 on 2026-08-18 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shyland', '0049_character_plunder_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='MCEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stream_id', models.CharField(max_length=32, unique=True)),
                ('ts', models.DateTimeField(db_index=True)),
                ('kind', models.CharField(max_length=16)),
                ('actor_id', models.BigIntegerField(blank=True, null=True)),
                ('actor_name', models.CharField(blank=True, default='', max_length=64)),
                ('room_id', models.BigIntegerField(blank=True, null=True)),
                ('audience', models.JSONField(blank=True, default=list)),
                ('data', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'indexes': [models.Index(fields=['kind', 'ts'], name='shyland_mce_kind_f26ab8_idx'), models.Index(fields=['actor_id', 'ts'], name='shyland_mce_actor_i_850b49_idx'), models.Index(fields=['room_id', 'ts'], name='shyland_mce_room_id_c4abc2_idx')],
            },
        ),
    ]
