# Generated by Django 5.2.17 on 2026-08-21 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shyland', '0051_create_shyland_agents_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='MCKillSwitch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('killed', models.BooleanField(default=False)),
                ('flipped_at', models.DateTimeField(blank=True, null=True)),
                ('flipped_by', models.CharField(blank=True, default='', max_length=64)),
            ],
        ),
    ]
