# Generated by Django 5.2.17 on 2026-08-22 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shyland', '0052_mckillswitch'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='outfit_snapshot',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
