# Generated by Django 5.2.17 on 2026-08-27 16:06

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shyland', '0053_character_outfit_snapshot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('waypoint', 'Waypoint'), ('bundle', 'Bundle')], max_length=16)),
                ('name', models.CharField(max_length=60)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_memories', to=settings.AUTH_USER_MODEL)),
                ('taught_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taught_agent_memories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['agent', 'created_at'], name='shyland_age_agent_i_f1e570_idx')],
                'constraints': [models.UniqueConstraint(models.F('agent'), models.F('kind'), django.db.models.functions.text.Lower('name'), name='agentmemory_unique_agent_kind_name_ci')],
            },
        ),
    ]
