# Generated by Django 5.2.17 on 2026-08-30 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shyland', '0055_normalize_durability_posture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdefinition',
            name='durability_table',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='itemdefinition',
            name='primary_stats',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='itemdefinition',
            name='secondary_stat_pool',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='itemdefinition',
            name='valid_slots',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='iteminstance',
            name='rolled_primary_stats',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='iteminstance',
            name='rolled_secondary_stats',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddConstraint(
            model_name='itemdefinition',
            constraint=models.CheckConstraint(condition=models.Q(('durability_table', []), ('takes_durability_loss', True), _negated=True), name='durability_posture_coherent'),
        ),
    ]
