# Generated by Django 5.2.17 on 2026-09-14 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shyland', '0058_alter_effectcomponent_component_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='effectcomponent',
            name='magnitude2_base',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='effectcomponent',
            name='magnitude2_scaling',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='effectcomponent',
            name='no_expiry',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='effectdefinition',
            name='apply_text',
            field=models.TextField(blank=True, default='', help_text='Equip-time theater, one output line per newline-separated line.'),
        ),
        migrations.AddField(
            model_name='effectdefinition',
            name='is_curse',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='effectdefinition',
            name='memorial_text',
            field=models.TextField(blank=True, default='', help_text='Stamped onto the item as memorial_description at curse end.'),
        ),
        migrations.AddField(
            model_name='iteminstance',
            name='latent_curse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='latent_on_instances', to='shyland.effectdefinition'),
        ),
        migrations.AddField(
            model_name='iteminstance',
            name='memorial_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='effectcomponent',
            name='component_type',
            field=models.CharField(choices=[('restore_vitality', 'Restore Vitality'), ('restore_vitality_percent', 'Restore Vitality (percent of max)'), ('restore_acuity', 'Restore Acuity'), ('restore_longevity', 'Restore Longevity'), ('restore_longevity_percent', 'Restore Longevity (percent of max)'), ('dot_vitality', 'DoT Vitality'), ('dot_acuity', 'DoT Acuity'), ('dot_longevity', 'DoT Longevity'), ('hot_vitality', 'HoT Vitality'), ('hot_acuity', 'HoT Acuity'), ('hot_longevity', 'HoT Longevity'), ('shift_acuity_high', 'Shift Acuity High'), ('shift_acuity_low', 'Shift Acuity Low'), ('stat_bonus', 'Stat Bonus'), ('stat_penalty', 'Stat Penalty'), ('curse_generic', 'Curse Generic'), ('durability_restore', 'Durability Restore'), ('stat_cut_percent', 'Stat Cut (percent of current)'), ('cut_vitality_max', 'Cut Vitality Max'), ('cut_longevity_max', 'Cut Longevity Max'), ('damage_cut', 'Damage Cut'), ('armor_cut', 'Armor Cut'), ('floor_hold_vitality', 'Floor Hold Vitality')], max_length=30),
        ),
        migrations.CreateModel(
            name='CurseCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(default=1)),
                ('curse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_on', to='shyland.effectdefinition')),
                ('item_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curse_candidates', to='shyland.itemdefinition')),
            ],
            options={
                'unique_together': {('item_definition', 'curse')},
            },
        ),
    ]
