# Generated by Django 5.2.17 on 2026-09-22 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shyland', '0059_effectcomponent_magnitude2_base_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='effectdefinition',
            name='cleanse_price',
            field=models.PositiveBigIntegerField(default=0, help_text="v26.3 (#297): copper an NPC cleanser charges to lift this curse from a Mk 1 item; the charge is cleanse_price × the item's Mk tier. 0 on non-curses."),
        ),
        migrations.AddField(
            model_name='npcdefinition',
            name='is_cleanser',
            field=models.BooleanField(default=False, help_text='v26.3 (#297): this NPC lifts item curses and sweeps packs for them. The cleanse and inspect commands route to a living cleanser in the room.'),
        ),
    ]
